FROM python:3.11-alpine AS builder

RUN apk add --no-cache gcc musl-dev linux-headers

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

FROM python:3.11-alpine

WORKDIR /app


COPY --from=builder /install /usr/local

COPY app.py .
RUN adduser -D appuser
USER appuser

EXPOSE 5000

CMD ["python", "app.py"]
